title: "Changhyun Choi"
description: "Technical notes on robotics AI, AI systems performance, GPU optimization, and research."
url: "https://changhyun-choi-98.github.io"
baseurl: ""
theme: just-the-docs

search_enabled: true
heading_anchors: true
color_scheme: light

aux_links:
  GitHub Repository: https://github.com/Changhyun-Choi-98/changhyun-choi-98.github.io
